SECRET_KEY = 'KJKHTasdfeSDFGSDFG234qKHER'

PERMANENT_SESSION_LIFETIME = 120 * 60;
AUTO_LOGOUT_DELAY = 120 * 60;

MYSQL_DATABASE_USER = "carsharing_boi"
MYSQL_DATABASE_PASSWORD = "verysecure"
MYSQL_DATABASE_HOST = "localhost"
MYSQL_DATABASE_PORT = 3306
MYSQL_DATABASE_DB = "carsharingdb"

